blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name='blog'),
    path('post/<int:id>', views.single_post, name='single_post'),
    path('category_posts/<int:id>', views.category_posts, name='category_posts'),
    path('tags/<int:id>', views.tag_posts, name='tag_posts')

]

gangtalk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('restaurant/', include('restaurant.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

else:
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # settings.DE

blog/models.py
from django.db import models
from home.models import User

# Create your models here.

STATUS = (
       ('published', 'Published'),
       ('pending', 'Pending')
)


AUTHOR = (
       ('admin', 'Admin'),
       ('editor', 'Editor'),
       ('moderator', 'Moderator'),
)

class Categories(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Category"

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/post/feature_img/')
    gallery_1 = models.ImageField(upload_to='blog/post/feature_img/', blank=True, null=True)
    gallery_2 = models.ImageField(upload_to='blog/post/feature_img/', blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    content = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS, default='pending')
    is_featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)
    created_date = models.DateField(auto_now_add=True)
    edited_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

home/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_admin=False, is_staff=False, is_superuser=False, is_active=True):
        if not email:
            raise ValueError("User must have an email address")
        if not password:
            raise ValueError("User must have a Password")
        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.is_admin = is_admin
        user_obj.is_active = is_active
        user_obj.is_staff = is_staff
        user_obj.is_superuser = is_superuser
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True,
            is_admin=True,
            is_superuser=True
        )
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    phone = models.CharField(max_length=60)
    image = models.ImageField(upload_to='user', default='')
    password = models.CharField(max_length=90)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_fullname(self):
        return self.first_name + " " + self.last_name


class CompanyInfo(models.Model):
    title = models.CharField(max_length=120)
    name = models.CharField(max_length=100)
    tag_line = models.CharField(max_length=100)
    fav_icon = models.ImageField(upload_to="company_info/")
    logo = models.ImageField(upload_to="company_info/")
    footer_logo = models.ImageField(upload_to="company_info/")
    shop_address = models.CharField(max_length=200)
    phone = models.CharField(max_length=15)
    fax = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField()
    about = models.TextField()
    facebook = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Company Information'

    def __str__(self):
        return self.shop_address


class Shop(models.Model):
    shop_title = models.CharField(max_length=50)
    address = models.CharField(max_length=150)
    district = models.CharField(max_length=20, null=True, blank=True)
    phone = models.CharField(max_length=15)
    description = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.shop_title


class AboutUs(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    image = models.ImageField(upload_to='about/', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'About Us'

    def __str__(self):
        return self.title


class History(models.Model):
    experience = models.PositiveIntegerField(verbose_name="Experiance Year")
    happy_customer = models.PositiveIntegerField()
    avail_food_item = models.PositiveIntegerField()
    running_order = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'History'

    def __str__(self):
        return str(self.experience)


class Subscription(models.Model):
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Brand(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='chef_photo/')

    def __str__(self):
        return self.name


# Home page Models...


class MealTime(models.Model):
    name = models.CharField(max_length=100)
    duration = models.CharField(max_length=200)
    image = models.ImageField(upload_to='meal_time/')

    class Meta:
        verbose_name_plural = 'Meal Time'

    def __str__(self):
        return self.name


class Feature(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class FeatureItems(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    image = models.ImageField(upload_to="features/")
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Feature Items'

    def __str__(self):
        return self.title


class Slider(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="slider/")
    discount = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    phone = models.CharField(max_length=15)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} {self.subject}"

restaurant/models.py
from django.db import models

# Create your models here.


# This Section for Menu

class Meal_category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="meal_category/")
    
    class Meta:
        verbose_name_plural = 'Meal Category'

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Custom_order(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.TextField()
    phone = models.CharField(max_length=15)
    num_of_people = models.PositiveIntegerField(blank=True, null=True)
    date_time = models.DateTimeField()
    description = models.TextField()
    created_date = models.DateField(auto_now_add=True)
    is_response = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Custom Order'

    def __str__(self):
        return self.name


# This Section for Product


class Category(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product_tab(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = 'Offer Product Tab'

    def __str__(self):
        return self.name



class Offer(models.Model):
    offer_name = models.CharField(max_length=100)
    product_tab = models.ForeignKey(Product_tab,on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.offer_name


class Product(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to="product/")
    price = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True, null=True)
    category = models.ManyToManyField(Category)
    sku = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    in_stock = models.BooleanField(default=True)
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, blank=True, null=True)
    items = models.ManyToManyField(Item, blank=True, verbose_name="Items(For Catering & Menu Product)")
    meal_category = models.ForeignKey(Meal_category, on_delete=models.CASCADE, blank=True, null=True)
    is_catering = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.TextField()
    phone = models.CharField(max_length=15)
    num_of_table = models.PositiveIntegerField()
    num_of_people = models.PositiveIntegerField()
    date = models.DateField()
    time = models.TimeField()
    is_response = models.BooleanField(default=False)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def blog(request):
    posts = Post.objects.filter(status='published')
    recent_posts = Post.objects.filter(status='published').order_by('-id')[:5]
    categories = Categories.objects.filter().order_by('-id')[:5]
    tags = Tag.objects.all().order_by('id')[:10]
    # posts_list = Post.objects.filter(status='published')
    page = request.GET.get('page', 10)
    paginator = Paginator(posts, 10)
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)

    q = request.GET.get('search_word')
    if q is not None:
        search_p = posts.filter(
            Q(title__icontains=q) |
            Q(category__name__icontains=q) |
            Q(content__icontains=q)
            )
        if search_p:
            context = {
            'posts':search_p,
            'recent_posts':recent_posts,
            'categories':categories,
            'tags':tags,
            'pagi':post
            }
            return render(request, 'pages/posts.html', context)
        else:
            messages.warning(request, "There is no post with your search keywod")
    context = {
        'posts':posts,
        'recent_posts':recent_posts,
        'categories':categories,
        'tags':tags,
        'pagi':post
    }
    return render(request, 'pages/posts.html', context)


def category_posts(request, id):
    posts = Post.objects.filter(status='published', category=id)
    if not posts:
        messages.warning(request, "There is no posts in this category")

    recent_posts = Post.objects.filter(status='published').order_by('-id')[:5]
    categories = Categories.objects.filter().order_by('-id')[:5]
    tags = Tag.objects.all().order_by('id')[:10]

    page = request.GET.get('page', 10)
    paginator = Paginator(posts, 10)
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)

    q = request.GET.get('search_word')
    if q is not None:
        posts = Post.objects.filter(status='published')
        search_p = posts.filter(
            Q(title__icontains=q) |
            Q(category__name__icontains=q) |
            Q(content__icontains=q)
            )
        if search_p:
            context = {
            'posts':search_p,
            'recent_posts':recent_posts,
            'categories':categories,
            'tags':tags,
            'pagi':post
            }
            return render(request, 'pages/category_posts.html', context)
        else:
            messages.warning(request, "There is no post with your search keywod")
        
    context = {
        'posts':posts,
        'recent_posts':recent_posts,
        'categories':categories,
        'tags':tags,
        'pagi':post
    }
    return render(request, 'pages/category_posts.html', context)


def tag_posts(request, id):
    posts = Post.objects.filter(status='published', tags = id)
    if not posts:
        messages.warning(request, "There is no posts in this tags")
    recent_posts = Post.objects.filter(status='published').order_by('-id')[:5]
    categories = Categories.objects.filter().order_by('-id')[:5]
    tags = Tag.objects.all().order_by('id')[:10]

    page = request.GET.get('page', 10)
    paginator = Paginator(posts, 10)
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)

    q = request.GET.get('search_word')
    if q is not None:
        posts = Post.objects.filter(status='published')
        search_p = posts.filter(
            Q(title__icontains=q) |
            Q(category__name__icontains=q) |
            Q(content__icontains=q)
            )
        if search_p:
            context = {
            'posts':search_p,
            'recent_posts':recent_posts,
            'categories':categories,
            'tags':tags,
            'pagi':post
            }
            return render(request, 'pages/category_posts.html', context)
        else:
            messages.warning(request, "There is no post with your search keywod")


    context = {
            'posts':posts,
            'recent_posts':recent_posts,
            'categories':categories,
            'tags':tags
    }
    return render(request, 'pages/posts.html', context)


def single_post(request, id):
    post_obj = Post.objects.get(id=id)
    recent_posts = Post.objects.filter(status='published').order_by('-id')[:5]
    categories = Categories.objects.filter().order_by('-id')[:5]
    tags = Tag.objects.all().order_by('id')[:10]
    q = request.GET.get('search_word')
    posts = Post.objects.filter(status='published')
    if q is not None:
        search_p = posts.filter(
            Q(title__icontains=q) |
            Q(category__name__icontains=q) |
            Q(content__icontains=q)
            )
        if search_p:
            context = {
            'posts':search_p,
            'recent_posts':recent_posts,
            'categories':categories,
            'tags':tags
            }
            return render(request, 'pages/posts.html', context)
        else:
            messages.warning(request, "There is no post with your search keywod")

    context = {
        'post':post_obj,
        'recent_posts':recent_posts,
        'categories':categories
    }
    return render(request, 'pages/single_post.html', context)

templates/pages/index.html
{% extends 'base.html' %}


{% load static %}
{% load mathfilters %}

{% block title %} {{ contact.name }} | {{ contact.tag_line }} {% endblock %}

{% block content %}

<!-- Start Slider Section -->
{% include 'sections/slider.html' %}
<!-- End Slider Section -->


<!-- Start Gang Talk Cafe Section -->
<section class="gang-talk-cafe-section" id="reach-to">
    <div class="row mx-5">
    <div class="col-lg-12">
        <div class="icon-default text-center" style="background-image: url({% static 'img/pattern/pattern-1.png' %}'');">
            <a href="#reach-to" class="scroll">
                <img src="{% static 'img/shape/scroll-arrow.png'%}" alt="not found" class="img-fluid">
            </a>
        </div>
    </div>
    </div>
    <div class="row align-items-center">
    <div class="col-lg-6">
        <div class="restant-img">
            <img src="{% static 'img/gang-talk-cafe/gang-talk-cafe.png'%}" alt="gang-talk-cafe" class="">
            <img src="{% static 'img/gang-talk-cafe/g-4.png'%}" alt="gang-talk-cafe" class="img-fluid">
            <img src="{% static 'img/gang-talk-cafe/g-2.png'%}" alt="gang-talk-cafe" class="img-fluid">
            <img src="{% static 'img/gang-talk-cafe/g-1.png'%}" alt="gang-talk-cafe" class="img-fluid">
            <img src="{% static 'img/gang-talk-cafe/g-3.png'%}" alt="gang-talk-cafe" class="img-fluid">
        </div>
    </div>
    <div class="col-lg-6">
        <div class="restant-content">
            <div class="section-title">
                <h2>{{ home_content.title }}</h2>
                <p>{{ home_content.description }}</p>
            </div>
            <a class="cmn-btn" href="{% url 'about' %}">Know More</a>
        </div>
    </div>
    </div>
</section>
<!-- End Gang Talk Cafe Section -->

<!-- Start Menu Section -->
<section class="menu-section" style="background-image: url({% static 'img/menu/menu-bg.jpg'%});">
    <div class="row mx-5">
        <div class="col-lg-12">
            <div class="icon-default text-center" style="background-image: url({% static 'img/pattern/pattern-2.png'%});">
                    <img src="{% static 'img/pattern/icon-2.png'%}" alt="not found" class="img-fluid">
            </div>
        </div>
        <div class="col-lg-12">
            <div class="menu-title text-center">
                <h2>Our Special Menu</h2>
                <p>The role of a good cook ware in the preparation of a sumptuous meal cannot be over emphasized then one consider white bread. Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis.</p>
            </div>
        </div>
    </div>
    <div class="row mx-5 mt-5">
            <div class="gallery-filter mb-5">
                <ul class="list-unstyled">
                    <li class="active" data-filter="*">All</li>
                    {% for i in meal_category %}
                    <li data-filter=".{{ i|lower }}">{{ i }}</li>
                    {% endfor %}
                </ul>
            </div>
            
            <div class="gallery mt-5 text-white">
                {% for i in meal_category %}
                {% for item in i.product_set.all|slice:":20" %}   
                {% if item.is_active %}             
                <div class="col-md-6 col-sm-6 col-xs-12 isotope-item {{ i|lower }} mb-5">
                    <div class="menu-list">
                        <span class="menu-list-product">
                            <img width="80" height="80" src="{{ item.image.url }}" alt="">
                        </span>
                        <h5>{{ item.name }} <span>৳ {% if item.discount %} {{ item.price|sub:item.discount }} {% else %}  {{ item.price }} {%endif%}</span></h5>
                        <p>{{ item.description|truncatewords:6 }}</p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}                
                {% endfor %}
            </div>
    </div>

</section>
<!-- End Menu Section -->




<!-- Start About Section -->

<!-- End About Section -->

<!-- Start Restaurant Timing Section -->
<section class="restaurant-timing-section">
    <div class="row mx-5">
        <div class="col-lg-12">
            <div class="icon-default text-center" style="background-image: url({% static 'img/pattern/pattern-1.png'%});">
                    <img src="{% static 'img/shape/icon6.png'%}" alt="not found" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="row mx-5 food-blog">
        {% for i in mealtime %}
        <div class="col-md-3 col-3 food-mxs">
            <div class="food-blog-inner">
                <div class="food-item">
                    <div class="food-item-inner">
                        <img src="{{ i.image.url }}" alt="img">
                    </div>
                </div>
                <h2>{{ i.name }}</h2>
                <span>{{ i.duration }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<!-- End Restaurant Timing Section -->

<!-- Feature Section Strart From Here -->
<section class="feature-area ptb-100">
    <div class="row mx-5">
        <div class="col-lg-12">
            <div class="icon-default text-center" style="background-image: url({% static 'img/feature/pattern-1.png'%});">
                    <img src="{% static 'img/feature/icon-1.png'%}" alt="not found" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="row mx-5">
        <div class="section-title text-center w-100">
            <h2>{{ feature.title }}</h2>
            <p>{{ feature.description }}</p>
        </div>
        <div class="feature-slider owl-theme owl-carousel">
            {% for i in feature.featureitems_set.all %}
            <div class="feature-item">
                <a>
                    <img src="{{ i.image.url }}" alt="Service" class="img-fluid f-img">
                    <img class="service-shape" src="{% static 'img/feature/service-shape.png'%}" alt="Service">
                    <h3>{{ i.title }}</h3>
                    <p>{{ i.content }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Feature Section Ended Here -->
{% endblock %}

templates/pages/menu.html
{% extends 'base.html' %}

{% load static %}
{% load mathfilters %}

{% block title %} {{ contact.name }} | Menu {% endblock %}

{% block content %}
<!-- Start sub-menu-banner-section -->
<div class="sub-menu-banner-section-1" style="background-color: #fff;">
    <div class="container" style="z-index: 9999;">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title">
                    <div class="title">
                        <h3 class="text-left">Menu</h3>
                    </div>
                    <nav aria-label="breadcrumb" style="display: flex; justify-content: flex-start; z-index: 999;">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                            <span class="test-separator"></span>
                            <li class="breadcrumb-item active" aria-current="page">Menu</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End sub-menu-banner-section -->



<!-- Start Menu Section -->
<section class="menu-section-2" id="reach-to">
    <div class="row mx-5">
        <div class="col-lg-12">
            <div class="icon-default text-center" style="background-image: url({% static 'img/pattern/pattern-3.png' %});">
                <a href="#reach-to" class="scroll">
                    <img src="{% static 'img/shape/scroll-arrow.png' %}" alt="not found" class="img-fluid">
                </a>
            </div>
        </div>
    </div>
    <div class="row mx-5 mb-5">
        {% for i in categories %}
        {% if forloop.counter|divisibleby:2 %}
        <div class="col-lg-6 col-sm-5 col-4 img-pos-1">
            <div class="menu-img text-center">
                <img src="{{ i.image.url }}" class="img-fluid" style="width: 55%;" alt="">
            </div>
        </div>
        <div class="col-lg-6 col-sm-7 col-8">
            <div class="title mb-4">
                <h3><span class="pr-2">0{{ forloop.counter }}.</span>{{ i.name }}</h3>
            </div>
            {% for j in i.product_set.all|slice:":10" %}
                {% if j.is_active and j.items.all %} 
                    <div class="menu-item text-white">
                        <h5>{{ j.name|upper }} <span class="ml-5">৳ {% if j.discount %} {{ j.price|sub:j.discount }} {% else %}  {{ j.price }} {%endif%}</span></h5>
                        <ul class="list-unstyled d-flex">
                            {% for k in j.items.all %}
                            <li class="mr-3"><i class="mr-2 fas fa-check-circle"></i>{{ k.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <div class="col-lg-6 col-sm-7 col-8">
            <div class="title mb-4">
                <h3><span class="pr-2">0{{ forloop.counter }}.</span>{{ i.name }}</h3>
            </div>
            {% for j in i.product_set.all|slice:":10" %}
                {% if j.is_active and j.items.all %} 
                    <div class="menu-item text-white">
                        <h5>{{ j.name|upper }} <span class="ml-5">৳ {% if j.discount %} {{ j.price|sub:j.discount }} {% else %}  {{ j.price }} {%endif%}</span></h5>
                        <ul class="list-unstyled d-flex">
                            {% for k in j.items.all %}
                            <li class="mr-3"><i class="mr-2 fas fa-check-circle"></i>{{ k.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="col-lg-6 col-sm-5 col-4 img-pos-1">
            <div class="menu-img text-center">
                <img src="{{ i.image.url }}" class="img-fluid" style="width: 55%;" alt="">
            </div>
        </div>
        {% endif %}
        {% endfor %}
</section>
<!-- End Menu Section -->




<!-- Brand Section Start From Here -->
<!-- Start Brand Images Section -->
<section class="brand-img-section">
        <div class="row mx-5">
            <div class="col-md-12">
             <div id="owl-brand" class="owl-carousel owl-theme">
                 {% for i in brands %}
                <div class="item"><img src="{{ i.logo.url }}" title="{{ i.name }}" class="" alt=""></div>
                {% endfor %}
            </div>
            </div>
        </div>
</section>
<!-- Start Brand Images Section -->
<!-- Brand Section Ended Here -->

{% endblock %}